title: ∫created
description: I created and integrated it with ...
author: Sergey Polyarus
show_downloads: false
google_analytics: G-M5FFVQXXYY
theme: jekyll-theme-hacker
timezone: Europe/Paris

paginate: 4
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

jekyll_compose:
  post_default_front_matter:
    last_modified_at: 
    permalink: 
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags:

collections:
  projects:
    output: true
    permalink: /projects/:path/

social:
  github: icreated
  linkedin: sergey-polyarus-23537a4a
  stackoverflow: spok
  credly: sergey-polyarus
  
