on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Dart Sass
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget
          wget -qO- https://github.com/sass/dart-sass/releases/download/1.64.2/dart-sass-1.64.2-linux-x64.tar.gz | sudo tar -xz -C /usr/local
          echo "export PATH=/usr/local/dart-sass:\$PATH" >> ~/.bashrc
          source ~/.bashrc
          ls -l /usr/local/dart-sass
          /usr/local/dart-sass/sass --version

      - name: Install sass-embedded
        run: gem install sass-embedded -v 1.86.0

      - name: Debug Dependencies
        run: |
          ruby -v
          gem -v
          bundler -v
          which sass
          /usr/local/dart-sass/sass --version

      - name: Install Dependencies
        run: bundle install
